title: Philoshi Hacker
url: https://localan.github.io
theme: null

# Output markdown with Kramdown (GitHub Pages default)
markdown: kramdown

# Notes collection rendered at /notes/
collections:
  notes:
    output: true
    # Include subfolders in URLs (e.g., /notes/2025/sejarah-hacker/)
    permalink: /notes/:path/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note
